# This is a basic workflow to help you get started with Actions

name: Fifth Workflow
on:
  workflow_dispatch:

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "how are you"
